main: net.mpoisv.ban.Main
version: 1.0-SNAPSHOT
name: UUID-BAN
author: skyneton

api-version: 1.13
folia-supported: true

commands:
  uuid:
    description: UUID Ban Command
    permission: server.uuid.ban.*
    usage: /<command>
